# The General boot
# (c) Blackberry pi 2017




# Blackberry pi Mint an Operating system made by Articuno1234
# Please do not edit this file!



































try:
    import subprocess
    import sys
    import os
except ImportError:
        print("Error Requirements are not installed!")

IS_WINDOWS = os.name == "nt"
IS_MAC = sys.platform == "darwin"
INTERACTIVE_MODE = not len(sys.argv) > 1  # CLI flags = non-interactive


def clear_screen():
    if IS_WINDOWS:
        os.system("cls")
    else:
        os.system("clear")
        
def user_choice():
    return input("> ").lower().strip()

def wait():
    if INTERACTIVE_MODE:
        input("Press enter to continue.")

def load_startup():
    if INTERACTIVE_MODE:
        input("Press enter to Startup.")

def menu():
    clear_screen()
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n"
          "     Blackberry pi Mint      \n"
          "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    print("Auto Login in 5 seconds.....")
    import time
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Starting....")
    time.sleep(1)
         
            
def startup():
     clear_screen()
     print("")
     print("Starting import sys.... Done!")
     import sys
     print("Starting import os.... Done!")
     import os
     print("Starting import subprocess")
     import subprocess
     print("Starting import time")
     import time
     print("Starting import boot_start")
     from boot import boot_start
     print("Unpacking import(s)\n"
           "Done!\n"
           "Starting menu.... Done!")
     load_startup()
     menu()

start = startup()
print(start)
